### ISSUE TITLE
Does not work on debian

### ISSUE THREAD

**Issue by sobrinho** [radxa/aml-flash-tool#2]
Hi there,

If I workaround the /etc/lsb-release issue, I get a:

```
E: Unable to locate package lib32z1
E: Unable to locate package lib32stdc++6
E: Couldn't find any package by regex 'lib32stdc++6'
E: Unable to locate package lib32ncurses5
```

How to proceed?

**Comment by sobrinho** [comment]
Looks like the package isn't available for debian arm64, I will try x64.

**Comment by jack-ma** [comment]
It's x86 binary tool from amlogic, can not work directly on ARM.

**Comment by sobrinho** [comment]
Worked in a bare metal x86, virtualized x86 or arm64 on Apple Silicon using qemu didn't work, though.
